baseURL = "https://mojoauth.com/blog"
languageCode = "en-us"
title = "MojoAuth Blog"
publishDir = "public/blog"

# Enable for syntax highlighting
pygmentsClass = true
pygmentsCodefences = true
pygmentsStyle = "friendly"

[taxonomies]
  author = "author"
  tag = "tags"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
  linkedin = "https://www.linkedin.com/company/mojoauth"
  github = "https://github.com/MojoAuth"
  ogimage = "/blog/assets/images/logo.svg"
  tagline = "Secure and Delightful Passwordless Experience"
  description = "Get more signups and build trust using Passwordless Authentication"
  twitter = "@mojoauth"

enableRobotsTXT = true